version: "master-{build}"

os: Windows Server 2012
platform:
  - x64

environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24-x64"
    - ruby_version: "25-x64"
    - ruby_version: "26-x64"

clone_folder: c:\projects\mixlib-shellout
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

skip_commits:
  # version bumps by Expeditor happen as a separate commit after the merge, we can skip
  author: Chef Expeditor
  # if ONLY the files listed below are changed in a commit, skip
  files:
    - MAINTAINERS.md
    - MAINTAINERS.toml
    - CHANGELOG.md
    - RELEASE_NOTES.md

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem update --system
  - gem --version
  - gem install bundler --quiet --no-document
  - bundler --version

build_script:
  - bundle install

test_script:
  - bundle exec rspec
